root = "/app"
tmp_dir = "tmp"

[build]
cmd = "go build -ldflags=\"-s -w\" -o ./tmp/main ."
entrypoint = ["./tmp/main", "serve"]
delay = 100
exclude_dir = ["ui", "web/docs", "tmp", "data", "devstack"]
